In [ ]:
##https://stackabuse.com/image-recognition-in-python-with-tensorflow-and-keras/

In [19]:
# import libraries

import pandas as pd
import numpy as np

import os

# image read

import skimage.io

In [2]:
# read in the dataset

df = pd.read_csv('./data/chinese_mnist.csv')

display(df.head())
df.tail()

suite_id  sample_id  code  value character
0         1          1    10      9         九
1         1         10    10      9         九
2         1          2    10      9         九
3         1          3    10      9         九
4         1          4    10      9         九

suite_id  sample_id  code  value character
14995        99          5     9      8         八
14996        99          6     9      8         八
14997        99          7     9      8         八
14998        99          8     9      8         八
14999        99          9     9      8         八

In [27]:
# create a files variable that contains image files

path = './data/images/'
files = os.listdir(path)

print(len(files))

files[:10]

15001


['input_69_2_7.jpg',
 'input_11_7_12.jpg',
 'input_81_4_10.jpg',
 'input_84_6_1.jpg',
 'input_36_3_3.jpg',
 'input_38_7_15.jpg',
 'input_3_1_15.jpg',
 'input_75_2_13.jpg',
 'input_17_8_2.jpg',
 'input_61_4_7.jpg']

In [4]:
print(df.shape)
df.shape[0]

(15000, 5)


15000

In [5]:
# add a column to store file names that matches the information given in csv

file_names = []

for i in range(0, df.shape[0]):
    file_names.append(f"input_{df['suite_id'][i]}_{df['sample_id'][i]}_{df['code'][i]}.jpg")

df['file_names'] = file_names

In [6]:
print(df.shape)
df.head()

(15000, 6)


suite_id  sample_id  code  value character         file_names
0         1          1    10      9         九   input_1_1_10.jpg
1         1         10    10      9         九  input_1_10_10.jpg
2         1          2    10      9         九   input_1_2_10.jpg
3         1          3    10      9         九   input_1_3_10.jpg
4         1          4    10      9         九   input_1_4_10.jpg

In [9]:
df.tail()

suite_id  sample_id  code  value character        file_names
14995        99          5     9      8         八  input_99_5_9.jpg
14996        99          6     9      8         八  input_99_6_9.jpg
14997        99          7     9      8         八  input_99_7_9.jpg
14998        99          8     9      8         八  input_99_8_9.jpg
14999        99          9     9      8         八  input_99_9_9.jpg

In [10]:
# check for null values

df.isnull().sum()

suite_id      0
sample_id     0
code          0
value         0
character     0
file_names    0
dtype: int64

In [11]:
## check each column

print(len(df['suite_id'].unique()))
df['suite_id'].unique()

100


array([  1,  10, 100,  11,  12,  13,  14,  15,  16,  17,  18,  19,   2,
        20,  21,  22,  23,  24,  25,  26,  27,  28,  29,   3,  30,  31,
        32,  33,  34,  35,  36,  37,  38,  39,   4,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,   5,  50,  51,  52,  53,  54,  55,
        56,  57,  58,  59,   6,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,   7,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         8,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,   9,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

In [12]:
print(len(df['sample_id'].unique()))
df['sample_id'].unique()

10


array([ 1, 10,  2,  3,  4,  5,  6,  7,  8,  9])

In [13]:
print(len(df['code'].unique()))
df['code'].unique()

15


array([10, 11, 12, 13, 14, 15,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [14]:
print(len(df['value'].unique()))
df['value'].unique()

15


array([        9,        10,       100,      1000,     10000, 100000000,
               0,         1,         2,         3,         4,         5,
               6,         7,         8])

In [15]:
print(len(df['character'].unique()))
df['character'].unique()

15


array(['九', '十', '百', '千', '万', '亿', '零', '一', '二', '三', '四', '五', '六',
       '七', '八'], dtype=object)

In [34]:
# create lists of image pixel width and height

width = []
height = []

for i in range(len(files)):
    if files[i].endswith('jpg') == True:
        image = skimage.io.imread(path + files[i])
        width.append(image.shape[0])
        height.append(image.shape[1])
    
print(width[:5])
height[:5]

[64, 64, 64, 64, 64]


[64, 64, 64, 64, 64]

In [40]:
# check the values in width

print(min(width))
print(max(width))
print(np.mean(width))
len(width)

64
64
64.0


15000

In [41]:
# check the values in height

print(min(height))
print(max(height))
print(np.mean(height))
len(height)

64
64
64.0


15000

In [42]:
# add width and height to the dataframe

df['width'] = 64
df['height'] = 64

df.head()

suite_id  sample_id  code  value character         file_names  width  \
0         1          1    10      9         九   input_1_1_10.jpg     64   
1         1         10    10      9         九  input_1_10_10.jpg     64   
2         1          2    10      9         九   input_1_2_10.jpg     64   
3         1          3    10      9         九   input_1_3_10.jpg     64   
4         1          4    10      9         九   input_1_4_10.jpg     64   

   height  
0      64  
1      64  
2      64  
3      64  
4      64

In [43]:
df.to_csv('./data/final.csv', index = False)